version: "3"
services:
  qiushaocloud-nps-server:
    image: qiushaocloud/nps-server:latest
    container_name: qiushaocloud-nps-server
    network_mode: "host"
    restart: always
    volumes: 
      - ./conf:/etc/nps/conf:rw
    #ports:
    #  - "8000:8000"
    #  - "8080:8080/udp"
    #  - "8081:8081"
    #  - "80:80"
    #  - "443:443"
    #  - "22:22"
    #  - "3306:3306"
    #  - "6379:6379"