version: "3"
services:
  qiushaocloud-nps-server:
    image: qiushaocloud/nps-server:latest
    container_name: qiushaocloud-nps-server
    network_mode: "host"
    restart: always
    volumes: 
      - ./conf:/etc/nps/conf:rw
    environment:
      - TZ=Asia/Shanghai
      - RERUN_MAX_NPS_CPU=110 # 如果配置了该值，则会在服务端启动时，根据CPU使用率自动重启服务，防止CPU过高导致服务端卡死
    #ports:
    #  - "8000:8000"
    #  - "8080:8080/udp"
    #  - "8081:8081"
    #  - "80:80"
    #  - "443:443"
    #  - "22:22"
    #  - "3306:3306"
    #  - "6379:6379" 