version: "3"
services:
  qiushaocloud-npc-client:
    image: qiushaocloud/npc-client:latest
    container_name: qiushaocloud-npc-client
    network_mode: "host"
    restart: always
    volumes: 
      - ./conf:/etc/npc/conf:rw
      #- /etc/hosts:/etc/hosts
      #- /tmp/npcDownload:/tmp/npcDownload:rw
    environment:
      - TZ=Asia/Shanghai
      - RERUN_MAX_NPC_CPU=110 # 如果配置了该值，则会在客户端启动时，根据CPU使用率自动重启客户端，防止CPU过高导致客户端卡死
    #ports:
    #  - "8000:8000"
    #  - "8080:8080/udp"
    #  - "8081:8081"
    #  - "80:80"
    #  - "443:443"
    #  - "22:22"
    #  - "3306:3306"
    #  - "6379:6379"